### ISSUE TITLE
Frighteningly funny experience

### ISSUE THREAD

**Issue by ksylvan** [minemo/text-generation-webui-barktts#5]
![image](https://github.com/minemo/text-generation-webui-barktts/assets/1226059/41262b87-5a34-48c4-b4cc-dcd4db83918d)

With this setting, after a few chats, we have a cacophony of simultaneous voices.

[Bark TTS.zip](https://github.com/minemo/text-generation-webui-barktts/files/11429929/Bark.TTS.zip)

Not sure how we can fix this, but the problem is that with pygmalion-7b model running, and the autoplay setting, each chat response comes back, and then is repeated multiple times (sometimes with different voices) while pygmalion just keeps generating responses.

**Comment by drdrr** [comment]
Hmm... Not sure what's happening here, but you could check [my fork](https://github.com/drdrr/text-generation-webui-barktts) for now. I've fixed a streaming bug (which may cause it to generate audio multiple times for one message), but I'm still exploring how to generate better longer audio, so I haven't merged the branch yet.
Also, you could check [Bark Speaker Library](https://suno-ai.notion.site/8b8e8749ed514b0cbf3f699013548683?v=bc67cff786b04b50b3ceb756fd05f68c) for voice preset gender. Forced speaker may not work as you wish

**Comment by Shelkey** [comment]
> 

Getting the same issue, drdrr's fork didn't fix it for me, though it did fix the streaming problem. but all chats from my conversation get auto-played during each new generation.
Gunna keep using the last version for now.

**Comment by drdrr** [comment]
The autoplay issue should be fixed in [my latest commit](https://github.com/drdrr/text-generation-webui-barktts/commit/baa39aed5bd33e5b75c2af7c5ae9540523e4d642).

**Comment by Shelkey** [comment]
> The autoplay issue should be fixed in [my latest commit](https://github.com/drdrr/text-generation-webui-barktts/commit/baa39aed5bd33e5b75c2af7c5ae9540523e4d642).

Works for me, thanks!
